"""empty message

Revision ID: 06a2a80aad63
Revises: 
Create Date: 2018-11-27 22:35:23.266000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a2a80aad63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('salt', sa.String(length=30), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('loginfailure', sa.SmallInteger(), nullable=False),
    sa.Column('logintime', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.Integer(), nullable=False),
    sa.Column('updatetime', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('createtime', sa.Integer(), nullable=False),
    sa.Column('updatetime', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('file', 'menu'), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=255), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('ismenu', sa.SmallInteger(), nullable=False),
    sa.Column('createtime', sa.Integer(), nullable=False),
    sa.Column('updatetime', sa.Integer(), nullable=False),
    sa.Column('weigh', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rule_pid'), 'rule', ['pid'], unique=False)
    op.create_index(op.f('ix_rule_weigh'), 'rule', ['weigh'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_weigh'), table_name='rule')
    op.drop_index(op.f('ix_rule_pid'), table_name='rule')
    op.drop_table('rule')
    op.drop_table('role')
    op.drop_table('admin')
    # ### end Alembic commands ###
